BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Training_Programs` (
	`Program_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`start_date`	INTEGER NOT NULL,
	`Max-occupancy`	INTEGER NOT NULL,
	`End_date`	INTEGER NOT NULL,
	`Employee_id`	INTEGER NOT NULL UNIQUE,
	`instructor`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `Products` (
	`Product_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Product_price`	REAL NOT NULL,
	`Product_title`	TEXT NOT NULL,
	`Product_type_id`	INTEGER NOT NULL UNIQUE,
	`Customer_id`	INTEGER NOT NULL UNIQUE,
	`Product_description`	TEXT UNIQUE
);
CREATE TABLE IF NOT EXISTS `Product_types` (
	`Product_type_Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Product_type`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `Payment_types` (
	`Payment_type_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Account_number`	INTEGER NOT NULL UNIQUE,
	`Payment_type`	BLOB NOT NULL,
	`Customer_id`	INTEGER NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS `Orders` (
	`Order_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Product_id`	INTEGER NOT NULL UNIQUE,
	`Customer_id`	INTEGER NOT NULL UNIQUE,
	`Payment_type_id`	INTEGER NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS `Employees` (
	`Employee_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Job_title`	BLOB NOT NULL,
	`First_name`	TEXT NOT NULL,
	`Last_name`	TEXT NOT NULL,
	`Employee_type_id`	INTEGER NOT NULL UNIQUE,
	`Computer_id`	INTEGER NOT NULL UNIQUE,
	`Department_id`	INTEGER NOT NULL UNIQUE,
	`Training_program_id`	INTEGER NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS `Employee_Types` (
	`Employee_type_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Employee_id`	INTEGER NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS `Department` (
	`Department_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Employee_type_id`	INTEGER NOT NULL UNIQUE,
	`Employee_id`	INTEGER NOT NULL UNIQUE,
	`Supervisor`	TEXT NOT NULL,
	`Expense_budget`	REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS `Customers` (
	`Customer_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`email`	TEXT NOT NULL UNIQUE,
	`first_name`	TEXT NOT NULL,
	`last_name`	TEXT NOT NULL,
	`last_date_used`	INTEGER NOT NULL,
	`Product_Id`	INTEGER NOT NULL UNIQUE,
	`Order_Id`	INTEGER NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS `Computers` (
	`computer_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`employee_id`	INTEGER NOT NULL UNIQUE,
	`decommission_date`	INTEGER NOT NULL,
	`purchase_date`	INTEGER NOT NULL
);
COMMIT;
